name: Build Docker Image

on:
  push:
    branches:
        - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/tomsonne/holbertonschool-continuous_integrations:latest \
            -t ghcr.io/tomsonne/holbertonschool-continuous_integrations:${{ github.sha }} \
            .
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Push Docker image
        run: |
          docker push ghcr.io/tomsonne/holbertonschool-continuous_integrations:latest
          docker push ghcr.io/tomsonne/holbertonschool-continuous_integrations:${{ github.sha }}
          